### ISSUE TITLE
не колхозь, используй нормальный naming

### ISSUE THREAD

**Issue by artbobrov** [Vagabun/white_belt#3]
https://github.com/Vagabun/white_belt/blob/576dc73ddea03ab3acb359a2ac8054c9b01f14ab/second_week/set/main.cpp#L14

**Comment by Vagabun** [comment]
:neutral_face:
![capture](https://user-images.githubusercontent.com/16858610/29497947-543c1152-85f2-11e7-8723-1cf09ab0218a.JPG)
